// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPDGUndStJhSqEsvSrHCVxYuK-oVId7LA',
    appId: '1:834333073152:web:46072df65b1b9b6e065de5',
    messagingSenderId: '834333073152',
    projectId: 'food-cart-488c1',
    authDomain: 'food-cart-488c1.firebaseapp.com',
    storageBucket: 'food-cart-488c1.firebasestorage.app',
    measurementId: 'G-QNY48P5064',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapE-xWfSWanhhcLNvQJiszaEenlc4iDA',
    appId: '1:834333073152:android:180cb638d3e52ce5065de5',
    messagingSenderId: '834333073152',
    projectId: 'food-cart-488c1',
    storageBucket: 'food-cart-488c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpHE8hCKhW31ghaI196lC1hbdZvSH0L84',
    appId: '1:834333073152:ios:2d750c5968e4a41b065de5',
    messagingSenderId: '834333073152',
    projectId: 'food-cart-488c1',
    storageBucket: 'food-cart-488c1.firebasestorage.app',
    iosBundleId: 'com.example.foodCartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpHE8hCKhW31ghaI196lC1hbdZvSH0L84',
    appId: '1:834333073152:ios:2d750c5968e4a41b065de5',
    messagingSenderId: '834333073152',
    projectId: 'food-cart-488c1',
    storageBucket: 'food-cart-488c1.firebasestorage.app',
    iosBundleId: 'com.example.foodCartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPDGUndStJhSqEsvSrHCVxYuK-oVId7LA',
    appId: '1:834333073152:web:c51b3ea7f28dbd88065de5',
    messagingSenderId: '834333073152',
    projectId: 'food-cart-488c1',
    authDomain: 'food-cart-488c1.firebaseapp.com',
    storageBucket: 'food-cart-488c1.firebasestorage.app',
    measurementId: 'G-L78063Q63V',
  );
}
